### ISSUE TITLE
PyPI code outdated

### ISSUE THREAD

**Issue by DanielDecker** [Qu4tro/homie-spec#5]
The code of this project at pypi.org is outdated.
Could you please create a new release for the current state and upload it to pypi.org? =)

**Comment by Qu4tro** [comment]
Yes. Apologies for the delay, I was on holidays. I will set up a github action to deploy it to PyPI.

As always, thanks for the heads up.

**Comment by DanielDecker** [comment]
Thank you! =)

**Comment by Qu4tro** [comment]
I've added a release for 0.5.0, with the current code base.

I'll keep the issue open, in case you find a problem with it. If it's all good, feel free to close it!

**Comment by DanielDecker** [comment]
I've just tested the 0.5.0 release with the sensor_reporter code. Everything works as expected. =)
